### ISSUE TITLE
Not found Doctrine\ODM\MongoDB\DocumentRepository class

### ISSUE THREAD

**Issue by pbrzoski** [radutopala/TSSAutomailerBundle#17]
I would like update this bundle, but when I do 'composer update' I got this error:

PHP Fatal error:  Class 'Doctrine\ODM\MongoDB\DocumentRepository' not found in vendor/tss/automailer-bundle/TSS/AutomailerBundle/Model/ODMRepository.php on line 8

**Comment by radutopala** [comment]
@pbrzoski we'll check asap

**Comment by DiliBau** [comment]
@radutopala @pbrzoski this is fixed in #18
